### ISSUE TITLE
Issue to PR automation seems to be broken

### ISSUE THREAD

**Issue by rajula96reddy** [kubernetes-sigs/contributor-tweets#120]
Our issue to PR automation seems to be broken after #104

We see the following error in the [action log](https://github.com/kubernetes-sigs/contributor-tweets/runs/4370908041?check_suite_focus=true#step:6:69)
```
   /usr/bin/git -c protocol.version=2 fetch --no-tags --progress --no-recurse-submodules --unshallow --force origin main:main
  fatal: couldn't find remote ref main
  Error: The process '/usr/bin/git' failed with exit code 128
```

We observed this in one of the recent issues https://github.com/kubernetes-sigs/contributor-tweets/issues/118

**Comment by Atharva-Shinde** [comment]
I suppose this may be happening because the GitHub actions (we are using in our tweet automation) were created at time when 'master' was the default branch.
As the default branch is now changed to 'main', I think we could try using latest versions of respective GitHub actions in our code.
I am suggesting this because the automation seemed to be working perfectly before changing master -> main

**Comment by Atharva-Shinde** [comment]
I guess we should change the name of contributor/tweets repository's default branch from **'master**' to **'main'**
I tried out in my local repository and it worked!

**Comment by Atharva-Shinde** [comment]
We should change the name of contributor/tweets repository's default branch from **'master**' to **'main'**
I tried out in my local repository and it worked!

**Comment by chris-short** [comment]
This should be resolved. We'll need to tweet something to confirm though.

**Comment by Atharva-Shinde** [comment]
it worked!  #124

**Comment by Debanitrkl** [comment]
Fixed
/close
