### ISSUE TITLE
Test: Creating a PR from a GH issue

### ISSUE THREAD

**Issue by rajula96reddy** [kubernetes-sigs/contributor-tweets#45]
**Provide the actual tweet content between the commented colons**

Hello! This tweet is created from a GH issue, which was PRed automatically.

**Comment by gkarthiks** [comment]
hi @rajula96reddy , there is no label as `tweet`, so if you want to add it, you have to create that in these places

* https://github.com/kubernetes/test-infra/blob/master/label_sync/labels.yaml
* https://github.com/kubernetes/test-infra/blob/master/label_sync/labels.md

Especially for k/community here https://github.com/kubernetes/test-infra/blob/master/label_sync/labels.md#labels-that-apply-to-kubernetescommunity-for-both-issues-and-prs

But if you don't want to create a new label, we can use an existing one. That needs to be added in the workflow file.

**Comment by rajula96reddy** [comment]
Hey @gkarthiks Thanks for the clarification. I did see the [action](https://github.com/kubernetes-sigs/contributor-tweets/runs/2846757798?check_suite_focus=true) is expecting a label.

@mrbobbytables Can we get your say on this? Should we create a new `tweet` label in the 'test-infra' or use an existing one?

**Comment by gkarthiks** [comment]
Yup, this was one of the requirements for this Action (details here 👉  https://github.com/kubernetes-sigs/contributor-tweets/pull/33#issuecomment-779785933).

I have also created a PR for the label `kind/tweet` here 👉  https://github.com/kubernetes/test-infra/pull/22618. Once that's approved, I will update the actions to expect the label with the name `kind/tweet` instead of `tweet`.

/cc @mrbobbytables @rajula96reddy @mbbroberg @parispittman

**Comment by rajula96reddy** [comment]
@gkarthiks Thanks a lot for creating the label! :heart:

**Comment by gkarthiks** [comment]
@rajula96reddy Let's close this issue please.
